coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        only_pulls: true
    patch:
      default:
        target: auto
        threshold: 0%
        only_pulls: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
