package com.indivaragroup.ageninlite.common.enums;

public enum AuditAction {
    REGISTER,
    REGISTER_WITH_REFERRAL,
    LOGIN,
    LOGIN_FAILED,
    INVITE_SENT,
    INVITE_ACCEPTED,
    INVITE_DECLINED,
    INVITE_CANCELLED,
    INVITATION_EXPIRED,
    TRANSACTION_CREATE,
    TRANSACTION_COMPLETE,
    TRANSACTION_FAILED,
    TRANSACTION_CANCELLED,
    COMMISSION_PAYOUT,
    USER_ACTIVATED,
    PRODUCT_SAVED,
    USER_DELETED
}
